//! Bench output formats.
//!
//! Two outputs per run:
//! - **CSV** — one row per `TickSample`, raw audit data. Header = column
//!   names from `TickSample::csv_header`.
//! - **Markdown** — human-readable report including:
//!   - run metadata + caveats
//!   - per-metric definitions (so the reader doesn't need to read Rust)
//!   - observed vs expected with citations inline
//!   - composite score + verdict
//!
//! The Markdown output is the primary deliverable for ecologist review.
//! It must be self-contained: every term used should be defined, every
//! number cited.

use std::fmt::Write as FmtWrite;

use crate::bench::expected::{Citation, ExpectedRange, SpeciesExpectations, Tolerance};
use crate::bench::metrics::{ALL_METRICS, MetricDefinition, TickSample};
use crate::bench::run::BenchResult;

/// Render the sample timeline as CSV. First line is header.
pub fn render_csv(result: &BenchResult) -> String {
    let mut out = String::with_capacity(result.samples.len() * 80);
    out.push_str(&TickSample::csv_header().join(","));
    out.push('\n');
    for s in &result.samples {
        out.push_str(&s.to_csv_row());
        out.push('\n');
    }
    out
}

/// Render the full Markdown report. Self-contained; one species per file.
pub fn render_markdown(result: &BenchResult) -> String {
    let mut out = String::with_capacity(8192);

    writeln!(out, "# Species Bench Report — {}", result.species_id).ok();
    writeln!(out).ok();
    writeln!(
        out,
        "Generated by `antcolony-sim::bench`. This report is intended for \
         ecologist review of the simulation's species fidelity."
    )
    .ok();
    writeln!(out).ok();

    // ---- Run metadata ----
    writeln!(out, "## Run Configuration").ok();
    writeln!(out).ok();
    writeln!(out, "```").ok();
    writeln!(out, "{}", result.config_summary).ok();
    writeln!(out, "```").ok();
    writeln!(out).ok();

    // ---- Caveats ----
    if !result.caveats.is_empty() {
        writeln!(out, "## Caveats").ok();
        writeln!(out).ok();
        for c in &result.caveats {
            writeln!(out, "- {c}").ok();
        }
        writeln!(out).ok();
    }

    // ---- Composite verdict ----
    writeln!(out, "## Verdict").ok();
    writeln!(out).ok();
    if let Some(score) = result.score.composite_0_to_100() {
        let verdict = if score >= 80.0 {
            "[HEALTHY] species behaves within literature ranges."
        } else if score >= 60.0 {
            "[MARGINAL] review individual metrics; some divergence from literature."
        } else if score >= 30.0 {
            "[CONCERNING] multiple metrics out of literature range."
        } else {
            "[FAILED] colony did not survive or showed pathological behavior."
        };
        writeln!(out, "**Composite score: {score:.1}/100** — {verdict}").ok();
    } else {
        writeln!(out, "**Composite score: n/a** — no metrics computable.").ok();
    }
    writeln!(out).ok();

    // ---- Per-metric breakdown ----
    writeln!(out, "## Metric Breakdown").ok();
    writeln!(out).ok();
    writeln!(
        out,
        "Each row below is one metric. \"What we measured\" defines the \
         metric in plain English; \"Observed\" is what the sim produced; \
         \"Interpretation\" explains how to read the value."
    )
    .ok();
    writeln!(out).ok();

    write_metric_row(
        &mut out,
        &ALL_METRICS[0], // colony_survival
        result.score.colony_survival,
    );
    write_metric_row(&mut out, &ALL_METRICS[1], result.score.queen_survival);
    write_metric_row(
        &mut out,
        &ALL_METRICS[2],
        result.score.brood_pipeline_health,
    );
    write_metric_row(
        &mut out,
        &ALL_METRICS[3],
        result.score.population_stability,
    );
    write_metric_row(&mut out, &ALL_METRICS[4], result.score.food_economy);
    write_metric_row(
        &mut out,
        &ALL_METRICS[5],
        result.score.hibernation_compliance,
    );

    // ---- Expected ranges from literature ----
    if let Some(exp) = &result.expectations {
        write_expectations_section(&mut out, exp, &result.samples);
    } else {
        writeln!(out, "## Expected Ranges").ok();
        writeln!(out).ok();
        writeln!(
            out,
            "_No expected-range table for this species. Add a \
             `SpeciesExpectations` entry in `src/bench/expected.rs` to \
             enable comparison against literature._"
        )
        .ok();
        writeln!(out).ok();
    }

    // ---- Timeline summary (sparse — full data in CSV) ----
    write_timeline_summary(&mut out, &result.samples);

    out
}

fn write_metric_row(out: &mut String, def: &MetricDefinition, value: Option<f64>) {
    writeln!(out, "### {}", def.human_name).ok();
    writeln!(out).ok();
    writeln!(out, "**What we measured:** {}", def.human_definition).ok();
    writeln!(out).ok();
    writeln!(out, "**Units:** {}", def.units).ok();
    writeln!(out).ok();
    let observed = match value {
        Some(v) => format!("{v:.4}"),
        None => "n/a (not computable for this run)".to_string(),
    };
    writeln!(out, "**Observed:** `{observed}`").ok();
    writeln!(out).ok();
    writeln!(out, "**Interpretation:** {}", def.interpretation).ok();
    writeln!(out).ok();
}

fn write_expectations_section(
    out: &mut String,
    exp: &SpeciesExpectations,
    samples: &[TickSample],
) {
    writeln!(out, "## Literature Expectations").ok();
    writeln!(out).ok();
    writeln!(
        out,
        "Source-of-truth doc: [`{}`](../../{}). Key references:",
        exp.doc_path, exp.doc_path
    )
    .ok();
    writeln!(out).ok();
    for src in exp.key_sources {
        writeln!(out, "- {src}").ok();
    }
    writeln!(out).ok();
    writeln!(
        out,
        "The table below pairs each expected range with the **value the sim \
         produced**. \"Tolerance\" is how loose the comparison is, calibrated \
         to natural variance in the cited literature."
    )
    .ok();
    writeln!(out).ok();

    let observed_year_5_workers = sample_at_year(samples, 5).map(|s| s.workers as f64);
    let observed_brood = sample_at_year(samples, 5).map(|s| (s.eggs + s.larvae + s.pupae) as f64);
    let observed_queen_alive = sample_at_year(samples, 5)
        .map(|s| if s.queens_alive > 0 { 1.0 } else { 0.0 });
    let observed_first_egg_day = first_egg_day(samples).map(|d| d as f64);
    let observed_food_year_5 = food_returned_in_year(samples, 5);

    write_expectation_row(out, "year_5_workers", &exp.year_5_workers, observed_year_5_workers);
    write_expectation_row(
        out,
        "year_5_brood_present",
        &exp.year_5_brood_present,
        observed_brood,
    );
    write_expectation_row(
        out,
        "year_5_food_returned_per_year",
        &exp.year_5_food_returned_per_year,
        observed_food_year_5,
    );
    write_expectation_row(
        out,
        "queen_alive_at_year_5",
        &exp.queen_alive_at_year_5,
        observed_queen_alive,
    );
    write_expectation_row(
        out,
        "days_to_first_egg",
        &exp.days_to_first_egg,
        observed_first_egg_day,
    );
}

fn write_expectation_row(
    out: &mut String,
    field_name: &str,
    er: &ExpectedRange,
    observed: Option<f64>,
) {
    writeln!(out, "### `{field_name}` — {}", er.human_name).ok();
    writeln!(out).ok();
    writeln!(out, "**What this is:** {}", er.human_why).ok();
    writeln!(out).ok();
    writeln!(out, "**Expected centroid:** {:.2}", er.centroid).ok();
    let (lo, hi) = er.tolerance.band();
    writeln!(
        out,
        "**Tolerance band:** {:.2} – {:.2} ({})",
        er.centroid * lo,
        er.centroid * hi,
        er.tolerance.human_description(),
    )
    .ok();
    writeln!(out, "**Source:** {}", citation_to_md(&er.citation)).ok();
    let obs_str = match observed {
        Some(v) => format!("{v:.2}"),
        None => "n/a".to_string(),
    };
    let verdict = match observed {
        Some(v) => verdict_for(er, v),
        None => "n/a".to_string(),
    };
    writeln!(out, "**Observed:** `{obs_str}` — **{verdict}**").ok();
    writeln!(out).ok();
}

fn citation_to_md(c: &Citation) -> String {
    match c {
        Citation::PeerReviewed(s) => format!("Peer-reviewed: *{s}*"),
        Citation::ReferenceWork(s) => format!("Reference: *{s}*"),
        Citation::TaxonomicDatabase(s) => format!("Taxonomic DB: {s}"),
        Citation::Extension(s) => format!("Extension: {s}"),
        Citation::LiteratureRange { low, high } => {
            format!("Literature range — low: *{low}* / high: *{high}*")
        }
        Citation::GamePacing(reason) => format!("[GAME-PACING — NOT biology]: {reason}"),
        Citation::InternalDoc(s) => format!("Internal doc: `{s}`"),
    }
}

fn verdict_for(er: &ExpectedRange, observed: f64) -> String {
    // GamePacing rows are NOT biology checks — render them with a distinct
    // marker so an ecologist scanning verdicts doesn't count them as
    // biological pass/fails. (Audit finding: these were previously rendered
    // identically to peer-reviewed checks, masking the distinction.)
    let game_pacing = matches!(er.citation, Citation::GamePacing(_));
    let (lo_mult, hi_mult) = er.tolerance.band();
    // Boolean special case: centroid 1.0 with Strict tolerance is the
    // harness's encoding of "expected-true." Treat anything ≥0.5 as in-band.
    // (Documented in docs/bench-audit.md §"Tolerance bands".)
    if matches!(er.tolerance, Tolerance::Strict) && (er.centroid - 1.0).abs() < f64::EPSILON {
        return if observed >= 0.5 {
            if game_pacing {
                "[PACING-PASS — NOT biology]"
            } else {
                "[IN BAND]"
            }
            .into()
        } else {
            if game_pacing {
                "[PACING-FAIL — NOT biology]"
            } else {
                "[OUT OF BAND]"
            }
            .into()
        };
    }
    let lo = er.centroid * lo_mult;
    let hi = er.centroid * hi_mult;
    if observed >= lo && observed <= hi {
        if game_pacing {
            "[PACING-IN-BAND — NOT biology]"
        } else {
            "[IN BAND]"
        }
        .into()
    } else if observed < lo {
        if game_pacing {
            "[PACING — below band]".into()
        } else {
            "[BELOW BAND] — investigate whether sim parameters understate growth".into()
        }
    } else {
        if game_pacing {
            "[PACING — above band]".into()
        } else {
            "[ABOVE BAND] — investigate whether sim parameters overstate growth".into()
        }
    }
}

/// Find the latest sample whose in_game_year is at least `year`.
/// Returns `None` if the run never reached the requested year — the
/// report renders `n/a` rather than silently substituting an earlier
/// sample (which would render an honest-looking but wrong verdict).
fn sample_at_year(samples: &[TickSample], year: u32) -> Option<&TickSample> {
    samples.iter().rev().find(|s| s.in_game_year >= year)
}

fn first_egg_day(samples: &[TickSample]) -> Option<u32> {
    samples.iter().find(|s| s.eggs > 0).map(|s| s.in_game_day)
}

fn food_returned_in_year(samples: &[TickSample], year: u32) -> Option<f64> {
    let in_year: Vec<&TickSample> = samples
        .iter()
        .filter(|s| s.in_game_year == year)
        .collect();
    if in_year.len() < 2 {
        return None;
    }
    let first = in_year.first()?;
    let last = in_year.last()?;
    Some(
        last.food_returned_cumulative
            .saturating_sub(first.food_returned_cumulative) as f64,
    )
}

fn write_timeline_summary(out: &mut String, samples: &[TickSample]) {
    writeln!(out, "## Timeline Summary").ok();
    writeln!(out).ok();
    writeln!(
        out,
        "_Full per-tick telemetry is in the accompanying CSV. Below is a \
         per-year digest._"
    )
    .ok();
    writeln!(out).ok();
    writeln!(
        out,
        "| Year | Workers | Eggs+Larvae+Pupae | Queens | Food Stored | Food Returned (cum) | Starvation Deaths |"
    )
    .ok();
    writeln!(out, "|-----:|--------:|------------------:|-------:|------------:|--------------------:|------------------:|").ok();
    let max_year = samples.last().map(|s| s.in_game_year).unwrap_or(0);
    for y in 0..=max_year {
        let last_in_year = samples.iter().rev().find(|s| s.in_game_year == y);
        if let Some(s) = last_in_year {
            writeln!(
                out,
                "| {} | {} | {} | {} | {:.1} | {} | {} |",
                y,
                s.workers,
                s.eggs + s.larvae + s.pupae,
                s.queens_alive,
                s.food_stored,
                s.food_returned_cumulative,
                s.starvation_deaths_cumulative,
            )
            .ok();
        }
    }
    writeln!(out).ok();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bench::metrics::SpeciesScore;
    use crate::bench::run::BenchResult;

    fn fake_result() -> BenchResult {
        BenchResult {
            species_id: "test".into(),
            config_summary: "species=test years=1.0".into(),
            samples: vec![],
            score: SpeciesScore {
                species_id: "test".into(),
                colony_survival: Some(1.0),
                queen_survival: Some(1.0),
                brood_pipeline_health: Some(0.9),
                population_stability: Some(0.2),
                food_economy: Some(1.2),
                hibernation_compliance: Some(1.0),
            },
            expectations: None,
            caveats: vec!["test caveat".into()],
        }
    }

    #[test]
    fn markdown_renders_without_panic() {
        let r = fake_result();
        let md = render_markdown(&r);
        assert!(md.contains("Species Bench Report"));
        assert!(md.contains("test caveat"));
        assert!(md.contains("Composite score"));
    }

    #[test]
    fn csv_includes_header_and_no_data_rows_for_empty() {
        let r = fake_result();
        let csv = render_csv(&r);
        let lines: Vec<&str> = csv.lines().collect();
        assert_eq!(lines.len(), 1, "header only when samples empty");
        assert!(lines[0].starts_with("tick,"));
    }
}
